import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Logo from "./components/logo"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#2E2E2E]">
        <Logo />  {/* Logo จะแสดงบนสุดในทุกหน้า */}
        {children}  {/* children จะถูกแทนที่ด้วย layout ภายใน */}
      </body>
    </html>
  );
}

